language: php

php:
  - 5.6
  - 7.3

services:
  - mysql

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: CHECKS=1 DEFAULT=0

    - php: 7.2
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - composer install --prefer-source --no-interaction

  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $CHECKS != 1 ]]; then composer require phpunit/phpunit:"^5.7|^6.0"; fi

  - cp config/app.php config/app_local.php

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi

  - if [[ $CHECKS == 1 ]]; then bin/cake dto generate -p Sandbox -v -d ; fi
  - if [[ $CHECKS == 1 ]]; then composer phpstan-setup && bin/cake code_completion generate && composer phpstan ; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

  - if [[ $CODECOVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml || true; fi
  - if [[ $CODECOVERAGE == 1 ]]; then wget -O codecov.sh https://codecov.io/bash; fi
  - if [[ $CODECOVERAGE == 1 ]]; then bash codecov.sh; fi

notifications:
  email: false
